FROM myoung34/github-runner:latest

COPY pubkey.gpg /tmp/pubkey.gpg
RUN sudo apt-key add /tmp/pubkey.gpg
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
RUN sudo apt update && sudo apt install yarn -y
RUN sudo pip install coscmd
